version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: snt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: snt_user
      POSTGRES_PASSWORD: snt_password
      POSTGRES_DB: snt_db
    ports:
      - "5434вщслук:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U snt_user -d snt_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
